use crate::cesu8_byte_buffer::ByteBuffer;
use crate::class_file_error::{ClassFileError, Result};

//https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Instruction {
    Aaload,
    Aastore,
    Aconst_null,
    Aload(u8),
    Aload_0,
    Aload_1,
    Aload_2,
    Aload_3,
    Anewarray(u16),
    Areturn,
    Arraylength,
    Astore(u8),
    Astore_0,
    Astore_1,
    Astore_2,
    Astore_3,
    Athrow,
    Baload,
    Bastore,
    Bipush(u8),
    Caload,
    Castore,
    Checkcast(u16),
    D2f,
    D2i,
    D2l,
    Dadd,
    Daload,
    Dastore,
    Dcmpg,
    Dcmpl,
    Dconst_0,
    Dconst_1,
    Ddiv,
    Dload(u8),
    Dload_0,
    Dload_1,
    Dload_2,
    Dload_3,
    Dmul,
    Dneg,
    Drem,
    Dreturn,
    Dstore(u8),
    Dstore_0,
    Dstore_1,
    Dstore_2,
    Dstore_3,
    Dsub,
    Dup,
    Dup_x1,
    Dup_x2,
    Dup2,
    Dup2_x1,
    Dup2_x2,
    F2d,
    F2i,
    F2l,
    Fadd,
    Faload,
    Fastore,
    Fcmpl,
    Fcmpg,
    Fconst_0,
    Fconst_1,
    Fconst_2,
    Fdiv,
    Fload(u8),
    Fload_0,
    Fload_1,
    Fload_2,
    Fload_3,
    Fmul,
    Fneg,
    Frem,
    Freturn,
    Fstore(u8),
    Fstore_0,
    Fstore_1,
    Fstore_2,
    Fstore_3,
    Fsub,
    Getfield(u16),
    Getstatic(u16),
    Goto(u16),
    Goto_w(u32),
    I2b,
    I2c,
    I2d,
    I2f,
    I2l,
    I2s,
    Iadd,
    Iaload,
    Iand,
    Iastore,
    Iconst_m1,
    Iconst_0,
    Iconst_1,
    Iconst_2,
    Iconst_3,
    Iconst_4,
    Iconst_5,
    Idiv,
}

pub fn read_one_instruction(buffer: &mut ByteBuffer) -> Result<Instruction> {
    let op_code = buffer.read_u8()?;
    let instruction = match op_code {
        0x32 => Instruction::Aaload,
        0x53 => Instruction::Aastore,
        0x1 => Instruction::Aconst_null,
        0x19 => Instruction::Aload(buffer.read_u8()?),
        0x2a => Instruction::Aload_0,
        0x2b => Instruction::Aload_1,
        0x2c => Instruction::Aload_2,
        0x2d => Instruction::Aload_3,
        0xbd => Instruction::Anewarray(buffer.read_u16()?),
        0xb0 => Instruction::Areturn,
        0xbe => Instruction::Arraylength,
        0x3a => Instruction::Astore(buffer.read_u8()?),
        0x4b => Instruction::Astore_0,
        0x4c => Instruction::Astore_1,
        0x4d => Instruction::Astore_2,
        0x4e => Instruction::Astore_3,
        0xbf => Instruction::Athrow,
        0x33 => Instruction::Baload,
        0x54 => Instruction::Bastore,
        0x10 => Instruction::Bipush(buffer.read_u8()?),
        0x34 => Instruction::Caload,
        0x55 => Instruction::Castore,
        0xc0 => Instruction::Checkcast(buffer.read_u16()?),
        0x90 => Instruction::D2f,
        0x8e => Instruction::D2i,
        0x8f => Instruction::D2l,
        0x63 => Instruction::Dadd,
        0x31 => Instruction::Daload,
        0x52 => Instruction::Dastore,
        0x98 => Instruction::Dcmpg,
        0x97 => Instruction::Dcmpl,
        0xe => Instruction::Dconst_0,
        0xf => Instruction::Dconst_1,
        0x6f => Instruction::Ddiv,
        0x18 => Instruction::Dload(buffer.read_u8()?),
        0x26 => Instruction::Dload_0,
        0x27 => Instruction::Dload_1,
        0x28 => Instruction::Dload_2,
        0x29 => Instruction::Dload_3,
        0x6b => Instruction::Dmul,
        0x77 => Instruction::Dneg,
        0x73 => Instruction::Drem,
        0xaf => Instruction::Dreturn,
        0x39 => Instruction::Dstore(buffer.read_u8()?),
        0x47 => Instruction::Dstore_0,
        0x48 => Instruction::Dstore_1,
        0x49 => Instruction::Dstore_2,
        0x4a => Instruction::Dstore_3,
        0x67 => Instruction::Dsub,
        0x59 => Instruction::Dup,
        0x5a => Instruction::Dup_x1,
        0x5b => Instruction::Dup_x2,
        0x5c => Instruction::Dup2,
        0x5d => Instruction::Dup2_x1,
        0x5e => Instruction::Dup2_x2,
        0x8d => Instruction::F2d,
        0x8b => Instruction::F2i,
        0x8c => Instruction::F2l,
        0x62 => Instruction::Fadd,
        0x30 => Instruction::Faload,
        0x51 => Instruction::Fastore,
        0x95 => Instruction::Fcmpl,
        0x96 => Instruction::Fcmpg,
        0xb => Instruction::Fconst_0,
        0xc => Instruction::Fconst_1,
        0xd => Instruction::Fconst_2,
        0x6e => Instruction::Fdiv,
        0x17 => Instruction::Fload(buffer.read_u8()?),
        0x22 => Instruction::Fload_0,
        0x23 => Instruction::Fload_1,
        0x24 => Instruction::Fload_2,
        0x25 => Instruction::Fload_3,
        0x6a => Instruction::Fmul,
        0x76 => Instruction::Fneg,
        0x72 => Instruction::Frem,
        0xae => Instruction::Freturn,
        0x38 => Instruction::Fstore(buffer.read_u8()?),
        0x43 => Instruction::Fstore_0,
        0x44 => Instruction::Fstore_1,
        0x45 => Instruction::Fstore_2,
        0x46 => Instruction::Fstore_3,
        0x66 => Instruction::Fsub,
        0xb4 => Instruction::Getfield(buffer.read_u16()?),
        0xb2 => Instruction::Getstatic(buffer.read_u16()?),
        0xa7 => Instruction::Goto(buffer.read_u16()?),
        0xc8 => Instruction::Goto_w(buffer.read_u32()?),
        0x91 => Instruction::I2b,
        0x92 => Instruction::I2c,
        0x87 => Instruction::I2d,
        0x86 => Instruction::I2f,
        0x85 => Instruction::I2l,
        0x93 => Instruction::I2s,
        0x60 => Instruction::Iadd,
        0x2e => Instruction::Iaload,
        0x7e => Instruction::Iand,
        0x4f => Instruction::Iastore,
        0x2 => Instruction::Iconst_m1,
        0x3 => Instruction::Iconst_0,
        0x4 => Instruction::Iconst_1,
        0x5 => Instruction::Iconst_2,
        0x6 => Instruction::Iconst_3,
        0x7 => Instruction::Iconst_4,
        0x8 => Instruction::Iconst_5,
        0x6c => Instruction::Idiv,

        op_code => {
            return Err(ClassFileError::InvalidCode(format!(
                "Invalid Op Code {op_code}"
            )));
        }
    };
    Ok(instruction)
}
