[package]
name = "class_file_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros = "0.25.2"
cesu8 = "1.1"
bitflags = "2.4.0"
log = "0.4.17"
